### ISSUE TITLE
Type alias for input objects

### ISSUE THREAD

**Issue by sporto** [dillonkearns/graphqelm#33]
I was using the generated input objects in my code e.g.

```
import Api.InputObject.UserAttrs exposing (UserAttrs)
```

As they were simple type aliases they were simple to use.

But now the lib generates:

```
type UserAttrs
    = UserAttrs { clientId : Int, name : String, timezone : String }
```

Meaning that if want to use this in my forms I need to unwrap and wrap `UserAttrs` all the time. I don't know why this type is needed, but ok.

So my possibilities atm are:

- Create functions to map each input object
- Duplicate the definition of the attrs

None is great. It would be nicer if the generator makes type aliases I can import e.g.

```
type alias UserAttrs
   = { clientId : Int, name : String, timezone : String }
   
type UserAttrsWrapped
    = UserAttrsWrapped UserAttrs
```

**Comment by dillonkearns** [comment]
Hey Sebastian, yes it is unfortunate that the wrapper is needed. The reason for it is that Input Objects can have recursive or circular references. The way that type aliases work in Elm, recursive or circular type alias references will not compile because they would generate infinitely large types. Graph.cool uses a lot of these kinds of types so issue #24 was reported and the wrapper was the fix for it.

It might not be too difficult to check whether any Input Object references are recursive or circular. But having a mixed use of wrapped types and non-wrapped types in the same generated code seems confusing. Perhaps since the majority of API's will not contain recursive or circular Input Objects, it might not be too confusing if no wrappers are used at all in these cases? I am definitely bummed to have to add this extra layer of abstraction, it makes it more difficult to discover how to use, debug, write the code, etc. But on the other hand, it could be confusing behavior if you add a circular or recursive Input Object reference to your API and suddenly the code dramatically changes (i.e. your consumer code has several compilation errors). Another option is that there could be a CLI flag to try to generate Input Objects without wrappers so it's more explicit. Any thoughts on that?

Either way, generating type aliases seems like a great idea when there are wrappers.

**Comment by dillonkearns** [comment]
I explored another possibility: automatically wrap the first level of InputObject in the generated code. That would mean that you would pass in the raw record as an argument. But then if that Input Object contains a nested InputObject, you would have to create the nested one using the Wrapper constructor.

Just exploring the different possibilities. When I look at [all the Input Objects in the Github API](https://developer.github.com/v4/input_object/commitauthor/), I actually notice that not a single one of them contains a nested Input Object. And this approach would work great for that situation. But I think it's still a fairly common idiom to have nested Input Objects. And it's unfortunate that you'd be using Input Objects in two pretty different ways... although it is predictable, you have to use the wrapper only in the instances where you're nesting it.

I'm curious if you have any thoughts are on all that @sporto.

**Comment by sporto** [comment]
Thanks for the explanation. I haven't come across with the need to having recursive input object, but I see the need.

I don't mind having to wrap the record at the very end:

```
|> with (Api.Mutation.addUser { attrs = Api.InputObject.UserAttrs attrs } response)
```

As long as I have a type alias for `UserAttrs` that I can use.

However not having to wrap would be even better. I think that consistency is very important, so if wrapping is needed sometimes, then wrapping should be used all the time.

Maybe the mutation could have two functions? One where the inputs are wrapped and one where the inputs are not. But this might be even more confusing.

**Comment by dillonkearns** [comment]
Yeah, I've considered generating two functions in several different situations for Graphqelm but I think there always ends up being a simpler solution. I think that's probably a sign that the design isn't quite right in some way (at least that's been what I've concluded so far). Upon further reflection, I also think that having the generated code wrap the first level for you, and then the user needing to manually wrap any Input Objects within an Input Object would be confusing. When I imagine explaining that it seems like a nightmare, which similarly I think is a sign that there's something wrong with that design. Consistency is definitely extremely valuable for this library.

I'm actually starting to like the approach of:
* Check if any recursion or loops occur in any of the Input Objects in the schema
* If so, use wrappers everywhere (with type aliases, but you have to manually wrap them everywhere)
* If not, use type aliases only (no wrappers at all)

The reason I'm thinking this might work well is that the majority of users would just not have to use wrappers. If you use something like Graph.cool which generates a lot of nested types then you will need to use the wrappers, but it's unavoidable since that's needed to model the domain for these schemas. And I'm guessing that it's fairly rare that a user will introduce their own nested or recursive Input Objects so it won't be too confusing when that happens.

I was able to write a function that successfully determines whether there are any loops (circular or recursive Input Objects) in the schema. I'd like to try this approach. Unless you have any concerns, I'm open to feedback! Thanks for the discussion, it's helpful to bounce ideas back and forth.

**Comment by sporto** [comment]
Hmm, this worries me if I have understood this correctly. 

So if later in my project I introduce a recursive input object, then the generator will change the api for all mutations I already had? So I will need to fix all working mutations I already had? 

Then if I happen to remove that recursive input object, I will need to fix everything again.

This doesn't sound very appealing. At this point I would prefer that some mutations require wrappers and other don't, or all of them do.

**Comment by dillonkearns** [comment]
@sporto yeah you're right, that would be frustrating behavior and perhaps I underestimate how frequently that could happen as an API evolves.

I think I'll try this other approach then of using wrappers for some and not for others. It's still not ideal, but it seems like reducing the extra wrapper layer is worthwhile since the majority of input objects will not need it. I've got the codegen working for this and I think the pros outweigh the cons:

*Pros*

* The majority of users probably won't ever have to deal with an Input Object wrapper
* Even if you do have some loops in your codebase, you only need them for those Input Objects that contain loops.
* If you introduce a loop, all the other Input Objects won't suddenly change and stop compiling.

*Cons*
* The Input Object that you introduce a loop in will change and stop compiling when it goes from no loop to having a loop. (This seems fairly reasonable to me).
* Having/not having wrappers is inconsistent in the case that you have some recursive or circular input objects in your schema. (Not ideal, but I think the pros outweigh this con. And there is at least a consistent logic to why this happens.)

A note explaining that an input object is Recursive or Circular in the doc comments I think could make this a little less confusing.

**Comment by dillonkearns** [comment]
@sporto @nicolasartman @Frozen666 I just published a change with the above approach (npm version `3.1.0`). I'm open to feedback if this approach seems confusing or like it could be improved.

**Comment by dillonkearns** [comment]
npm version `3.1.1` generates type aliases as well for looped Input Objects. It includes comments linking to this discussion.

```haskell
{-| Type alias for the `CircularOne` attributes. Note that this type
needs to use the `CircularOne` type (not just a plain type alias) because it has
references to itself either directly (recursive) or indirectly (circular). See
<https://github.com/dillonkearns/graphqelm/issues/33>.
-}
type alias CircularOneRaw =
    { circularTwo : OptionalArgument CircularTwo }


{-| Type for the CircularOne input object.
-}
type CircularOne
    = CircularOne CircularOneRaw
```

**Comment by sporto** [comment]
Seems to me like this can be closed now, thanks.
