### ISSUE TITLE
Missing import in generated module

### ISSUE THREAD

**Issue by slikts** [dillonkearns/graphqelm#45]
The type `RootQuery` is not imported but used in a generated file, preventing it from compiling.

Here's the generated file with the error: https://gitlab.com/slikts/scraper-front/blob/master/src/elm/ScraperData/Object/CreateSubscriptionPayload.elm

Here's the GraphQL schema dump the code was generated from: https://gist.github.com/slikts/7c69bf77d3e4152b053b353be6ad1661

Graphqelm package version 10.0.0

**Comment by slikts** [comment]
From what I can tell all `Object` modules are missing the `RootQuery` import.

**Comment by dillonkearns** [comment]
Thanks for reporting the issue @slikts, the fix is as simple as adding that import line like this one to the analagous Object generator file: https://github.com/dillonkearns/graphqelm/blob/master/src/Graphqelm/Generator/Mutation.elm#L32. And I’ll need to expose all the `Operation` types in these files. I’ll take care of this as soon as I’m back at a computer. Thanks!
