### ISSUE TITLE
The argument to function `send` is causing a mismatch: RemoteData.fromResult >> GotResponse

### ISSUE THREAD

**Issue by rofrol** [dillonkearns/graphqelm#56]
with `"dillonkearns/graphqelm": "11.0.0 <= v < 11.0.1"` or  `"dillonkearns/graphqelm": "11.1.0 <= v < 11.1.1"`

and using code from https://ellie-app.com/55w73b8MDa1/0

```
Starting downloads...

  ● elm-community/string-extra 1.4.0
  ● elm-community/list-extra 7.1.0
  ● Skinney/murmur3 2.0.6
  ● dillonkearns/graphqelm 11.1.0
  ● lukewestby/elm-string-interpolate 1.0.2
  ● elm-lang/http 1.0.0
  ● elm-lang/core 5.1.1
  ● rtfeldman/elm-css-util 1.0.2
  ● krisajenkins/remotedata 4.3.3
  ● elm-lang/websocket 1.0.2
  ● elm-lang/html 2.0.0
  ● elm-community/json-extra 2.7.0
  ● elm-lang/virtual-dom 2.0.4
  ● rtfeldman/hex 1.0.0
  ● rtfeldman/elm-css 13.1.1

Packages configured successfully!
Detected errors in 1 module.


-- TYPE MISMATCH -------------------------------------------------- src/Main.elm

The argument to function `send` is causing a mismatch.

121|                      Http.send (RemoteData.fromResult >> GotResponse)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Function `send` is expecting the argument to be:

    Result (Graphqelm.Http.Error decodesTo) decodesTo -> msg

But it is:

    Result Graphqelm.Http.Error Response -> Msg
```

**Comment by rofrol** [comment]
Looks like the code in https://github.com/dillonkearns/graphqelm/tree/11.1.0/examples/src works. So only this https://github.com/dillonkearns/graphqelm-demo/releases needs to be update to have working ellie with new version.

**Comment by dillonkearns** [comment]
Hey @rofrol, yes that's right the Ellie example is not using the latest version of Graphqelm so if you want to copy that code you would need to install an older version. But the code in [the `examples` folder](https://github.com/dillonkearns/graphqelm/tree/master/examples/src) is always up-to-date.

It's a bit tedious to update the Ellie code unfortunately because I have to publish two different packages (Graphqelm itself and the graphqelm-demo package). I'll update it soon though. Cheers!
