### ISSUE TITLE
Documentation or example on how to do mutations

### ISSUE THREAD

**Issue by youroff** [dillonkearns/graphqelm#65]
I'm trying to learn how to execute mutations with `graphqelm` and it turned out pretty hard to figure out without some simple example or documentation. Can anyone add it, please? Probably it's something obvious for someone experienced with Elm, but I found it frustrating.

**Comment by dillonkearns** [comment]
Hello @youroff, I appreciate the constructive suggestion! It's great to know what trips people up so I can improve the experience of learning about this library.

I added an example under [`examples/src/SimpleMutation.elm`](https://github.com/dillonkearns/graphqelm/blob/master/examples/src/SimpleMutation.elm). You can also see some basic docs for the associated functions if that's helpful, like http://package.elm-lang.org/packages/dillonkearns/graphqelm/11.2.0/Graphqelm-Http#mutationRequest.

I hope that helps. Let me know if there's anything else that is confusing. Thanks!

**Comment by dillonkearns** [comment]
And just to explain what's going on a bit, the way you do mutations is exactly the same except that the type of the base request is `Graphqelm.Operation.RootMutation` instead of `Graphqelm.Operation.RootQuery`, and you use `Graphqelm.Http.mutationRequest` instead of `Graphqelm.Http.queryRequest`. You can the `SimpleMutation.elm` example to [the `Starwars.elm` example](https://github.com/dillonkearns/graphqelm/blob/master/examples/src/Starwars.elm) and see these differences. Otherwise everything else is the same. Cheers!

**Comment by youroff** [comment]
Thank you, @dillonkearns! I think I advanced a bit further, but still stuck, cause simple mutation doesn't involve use of arguments or input objects. Here's what I'm trying to do:

```
-- I have this mutation generated
tokenCreate : TokenCreateRequiredArguments -> SelectionSet decodesTo Api.Object.Token -> Field (Maybe decodesTo) RootMutation
tokenCreate requiredArgs object =
    Object.selectionField "tokenCreate" [ Argument.required "email" requiredArgs.email Encode.string, Argument.required "password" requiredArgs.password Encode.string, Argument.required "role" requiredArgs.role (Encode.enum Api.Enum.Role.toString) ] object (identity >> Decode.nullable)
```

I used `TokenCreateRequiredArguments` type for form model (as type alias), so basically it's what comes to mutation function:
```
mutation : LoginModel -> SelectionSet Token RootMutation
mutation model =
    Mutation.selection Token
        |> with (Mutation.tokenCreate model _???_)
```

So I'm not sure what should I pass as a second argument, that has a signature `SelectionSet decodesTo Api.Object.Token`. The problem is that this is basically first thing with side effects that I'm trying to do with Elm, so I'm very sorry if this sounds dumb. In general what would be perfect for the beginners like me is a kind of write-up describing architecture and flow such as what function does what etc.

**Comment by dillonkearns** [comment]
Hey @youroff, I'm glad you figured it out! Let me know if you write a blog post, I can link to it on the Readme. I am also working on a gitbook here https://legacy.gitbook.com/book/dillonkearns/elm-graphql/detail. But I think details like this would be outside the scope of the main docs because they see more Elm fundamentals rather than grapghqelm-specific knowledge.

There are lots of friendly people willing to provide help any time in the elm-lang slack in #beginners and #graqhql, as well. I highly recommend checking that out. Cheers!

**Comment by tennety** [comment]
@youroff I'm in the exact position you were when you created this issue (hence this comment and not just a 👍 ). I'd love to see your write-up, or a link to any relevant elm-slack discussion. @dillonkearns Thanks for all your work!

**Comment by youroff** [comment]
@tennety I didn't do that yet and later had to switch to the other project for a while, but @dillonkearns's gitbook is actually a pretty good place to learn about SelectionSets, this is what I was struggling with mostly. If you want, I can create a gist with what I ended up with.

**Comment by tennety** [comment]
Cool, thanks both! Reading the book now (I had some issues accessing it before). I realized that the second argument to the mutation needed to be the fields I needed in the response, so I'm a little further along :)
