### ISSUE TITLE
Allow name of API to be set from CLI

### ISSUE THREAD

**Issue by martimatix** [dillonkearns/graphqelm#8]
This is a feature request for allowing users of graphqelm CLI to set the name of the API with an optional flag.

For example: `$ graphqelm  https://graphqelm.herokuapp.com/api --name swapi`

This would apply the `--name` argument to:
1. The top directory of the folder structure. In the example above, the top level folder would become `Swapi` as opposed to `Api`.
2. Each module generated by graphqelm. The module declaration would be appropriately namespaced. e.g. `module Swapi.Enum.Episode exposing (..)`

**Comment by dillonkearns** [comment]
Hey Mario, good news! I built that feature in a couple of days ago :-) It's in the latest npm package. You could just run `graphqelm https://graphqelm.herokuapp.com --base Swapi` (here's the [line in the usage output](https://github.com/dillonkearns/graphqelm/blob/2d4d7a9bba1ea9ada787273d0512acafe59544f0/src/graphqelm.ts#L12)). Currently it assumes that you make it capitalized so it's a proper elm module/folder name, and there's no check for that, so that could be improved. And there should probably be an example in the README.

**Comment by dillonkearns** [comment]
I'll leave this open to track that. I'm open to any other feedback as well!

**Comment by martimatix** [comment]
That's good news! It's been a couple of days since I updated graphqelm. 

Documentation of the feature in the readme would be nice so that future users can discover it.

Correcting the capitalisation would be a _nice to have_.

**Comment by dillonkearns** [comment]
I improved the usage instructions in the README and included the `--base` flag in the example there. Still need to make the `--base` flag less error-prone.

**Comment by dillonkearns** [comment]
Alright, I published a fix for this! I went with the simplest possible approach: check that the format is good as is with a regex check. I think that should be a pretty good UX, no mystery about certain rules for transforming it for the user to think about or to potentially introduce bugs.

https://github.com/dillonkearns/graphqelm/commit/2daa4ce6b21373e6a07dec3aeb414255b7d3ad9b

Closing this out.
